# This playbook contains docker actions that will be run on "remote" host.

- name: Install Python
  apt:
    name: ['python3', 'python3-pip']
    update_cache: true
    state: present
  tags:
    - instance-setup

- name: Add python alias
  lineinfile:
    dest: /home/ubuntu/.bash_aliases
    line: alias python='python3'
    state: present
    insertafter: EOF
    create: True
  tags:
    - instance-setup

- name: Install pip packages
  pip:
    name:
      - docker
      - docker-compose
  tags:
    - instance-setup