# This playbook contains docker actions that will be run on "remote" host.
 
# sudo apt-get install *
- name: Install docker packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
  tags:
    - instance-setup
 
# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - instance-setup
 
# sudo apt-key fingerprint 0EBFCD88
- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - instance-setup
 
# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - instance-setup
 
# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - instance-setup
 
# sudo apt-get install docker-ce=18.03.*
- name: Install docker
  apt:
    name: docker-ce=18.03.*
    state: present
    update_cache: yes
  notify: Start docker on boot
  tags:
    - instance-setup
 
# sudo groupadd docker
- name: Create "docker" group
  group:
    name: "{{ docker_group }}"
    state: present
  tags:
    - instance-setup
 
# sudo usermod -aG docker ubuntu
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "{{ remote_user }}"
    group: "{{ docker_group }}"
    append: yes
  tags:
    - instance-setup
    
# curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
- name: Fetch docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  tags:
    - instance-setup